config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders

  resources :carts
  get 'store/index'
  resources :products
  root :to => 'store#index', :as => 'store'
  resources :line_items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html





end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)

    if current_item
      current_item.quantity = current_item.quantity || 1 + 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index

    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin

      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart # {params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'

    else
      respond_to do |format|
        format.html # show.html.erb
       # format.xml { render :xml => @cart }
      end
    end

  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit

  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json



  def update



    respond_to do |format|
      if @cart.update(@cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end



end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title" >Your Cart</div>
<table>

  <%= render(cart.line_items) %>
  <tr class="total_line" >
    <td colspan="2" >Total</td>
    <td class="total_cell" ><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>

<%= button_to "Checkout", new_order_path, :method => :get %>
<%= button_to 'Empty cart', cart, :method => :delete,
              :confirm => 'Are you sure?' %>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/cart.html.erb
<%= render(cart.line_items) %>

<td class="total_cell" ><%= number_to_currency(cart.total_price) %></td>
</tr>

<%= button_to 'Empty cart', cart, :method => :delete,
              :confirm => 'Are you sure?' %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>




    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= button_to 'Empty cart', cart, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %>
<%= link_to 'Editar', edit_cart_path(@cart) %> |
<%= link_to 'Regresar', carts_path %>

<h2> Tus articulos </h2>



<ul>
  <div class="cart_title" >Your Cart</div>


</ul>


<table>

  <%= render(@cart.line_items) %>

  <tr class="total_line" >
    <td colspan="2" >Total</td>
    <td class="total_cell" ><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>


<%= button_to 'Empty cart', @cart, :method => :delete,
              :confirm => 'Are you sure?' %>